Introduction to the numpy

Function covered:-

1:-Array and its some operations

2:-Matrix and its operations

3:- Set operations

4:- Dimension change in the arrays

In [1]:
import numpy as np

In [2]:
#creating an 1D array of 10  elements
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr#for showing the array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# creating 2d array
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
#creating 3d array
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
#there are different operations performed on an array using different functions
#for checking the dimension of the array
a1=arr.ndim
a2=arr2.ndim
a3=arr3.ndim
print(a1,a2,a3)

1 2 3


In [6]:
#Indexing on the array:Indexing in NumPy arrays allows you to access
#specific elements or subsets of elements within the array
arr = np.array([1, 2, 3, 4, 5])

first_element = arr[0]      # Access the first element (1)
third_element = arr[2]      # Access the third element (3)
last_element = arr[-1]      # Access the last element (5)
print(first_element,third_element,last_element)
#for accessing the last element reverse indexing is used

1 3 5


In [7]:
#for accessing the element from 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

element = arr[1, 2]  # Access the element in the second row and third column (6)
print(element)

6


In [8]:
#for accessing from the 3D array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

element = arr[1, 0, 1]
print(element)
# Access the element in the second "depth",first row, and second column (6)

6


In [9]:
#arange function:-The np.arange() function in NumPy is used to create arrays with regularly spaced values
#syntax:- np.arange([start, ]stop, [step, ]dtype=None)
arr = np.arange(5)#arranging 5 elements from 0
print(arr)

arr2 = np.arange(2, 10, 2)#arranging an array starting at 2, ending before 10, and with a step of 2
print(arr2)

arr3 = np.arange(0, 1, 0.2)#arranging the elemets 0 to 1 with gap of 0.2
print(arr3)

arr4 = np.arange(1, 6, dtype=float)#arranging and specifying data type
print(arr4)

[0 1 2 3 4]
[2 4 6 8]
[0.  0.2 0.4 0.6 0.8]
[1. 2. 3. 4. 5.]


In [10]:
#slicing the array:-
#Slicing is a powerful feature in NumPy that allows you to extract and manipulate specific portions of an array
arr6=np.array([1,2,3,4,5,6,7,8,9,0])
print("The array is:- ",arr6)

## Extract elements from index 1 to 3 (inclusive of 1, exclusive of 3)
subarray=arr6[1:3]
print("The extacted element is:-",subarray)


The array is:-  [1 2 3 4 5 6 7 8 9 0]
The extacted element is:- [2 3]


In [11]:
#2d array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("the original array:-")
print(arr)

# Extract the second row
row = arr[1, :]
print("Extacting the second row:-")
print(row)

# Extract the first two columns
columns = arr[:, 0:2]
print("Extacting the first two columns row:-")
print(columns)

the original array:-
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Extacting the second row:-
[4 5 6]
Extacting the first two columns row:-
[[1 2]
 [4 5]
 [7 8]]


In [12]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr[-1::]# negative indexing

array([10])

In [13]:
arr[-1:-5:-1]

array([10,  9,  8,  7])

In [14]:
#linspace:-It  is a function in NumPy that is used to create an array of evenly spaced values over a specified range.
#syntax=numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

#Creating an array of 10 evenly spaced values between 0 and 1
arr = np.linspace(0, 1, 10)
print("01::-",arr)

#Creating an array of 5 evenly spaced values between 1 and 2 (exclusive of 2)
arr2 = np.linspace(1, 2, 5, endpoint=False)
print("02::-",arr2)

#Specifying the data type of the resulting array
arr3 = np.linspace(1, 10, 5, dtype=int)
print("03::-",arr3)

01::- [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
02::- [1.  1.2 1.4 1.6 1.8]
03::- [ 1  3  5  7 10]


In [15]:
#random function:-this module provides a variety of functions for generating random numbers and random arrays.
#generate the random array of 2rows and three columns
arr1=np.random.rand(2,3)
print(arr1)
#it will change the value if we run it as many times

[[0.72510316 0.88553427 0.90678225]
 [0.99299422 0.25417937 0.72080459]]


In [16]:
#for generating random 3 number from 1 to 10
arr2=np.random.randint(1,10,3)
print(arr2)

[3 9 4]


In [17]:
#Generates a 3x4 array of random values from the standard normal distribution
random_array = np.random.randn(3, 4)
print(random_array)

[[ 0.59287373 -0.01085901  0.45535529  1.66881232]
 [-0.90323481 -1.09674035 -0.34172977  0.55183224]
 [ 1.04756378  1.45493793  0.02393496 -0.986901  ]]


In [18]:
# numpy.random.uniform():
# Generates random values from a uniform distribution within a specified range:
value = np.random.uniform(5, 10)  # Generates a random value between 5 and 10
print(value)

8.519935114130135


In [19]:
# numpy.random.choice():
# Randomly selects elements from an input array:-
array = np.array([1, 2, 3, 4, 5])
choice1 = np.random.choice(array, size=3)
print(choice1)
# Randomly selects 3 elements from the array

[4 3 5]


In [20]:
# numpy.random.shuffle():
# Shuffles the elements of an array in place:
array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array)  # Shuffles the order of elements in the array
print(array)

[2 4 5 3 1]


In [21]:
# numpy.random.seed():
# Sets the seed for the random number generator, allowing for reproducibility:
np.random.seed(42)  # Set a seed value to generate the same random numbers in future runs
random_array = np.random.rand(3)  # Generates random values using the specified seed
print(random_array)

[0.37454012 0.95071431 0.73199394]


In [22]:
#logspace:-The numpy.logspace() function is useful for generating logarithmically spaced values,
#which is commonly used in various applications, including plotting on logarithmic scales
log_values = np.logspace(0, 1, 5)  # Generates 5 values from 10^0 to 10^1
print(log_values)

[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


In [23]:
# sample:-numpy.random.sample() is used to generate random floats in the specified range and size, often used for simulations and random data generation.
np.random.random_sample((2,3)) # Generates a 2x3 array of random floats

array([[0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [24]:
#matrix
#identity matrix:-In NumPy, you can create an identity matrix using the numpy.eye() function.

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("identity matrix using eye function:-")
print(identity_matrix)

identity_matrix2=np.identity(3)
print()#used only for space
print("Identity matrix using identity function:-")
print(identity_matrix2)

identity matrix using eye function:-
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Identity matrix using identity function:-
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#linear matrix with 10 zeros
zero_mat=np.zeros(10)
print(zero_mat)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [26]:
#matrix with 10 one's and int data type
ones_mat=np.ones(10,dtype=int)
print(ones_mat)

[1 1 1 1 1 1 1 1 1 1]


In [27]:
#matrix using full() function
#np.full() is a NumPy function that is used to create a new array filled with a specified constant value
#synatax:-numpy.full(shape, fill_value, dtype=None)
arr = np.full((3, 3), 5)
print(arr)


[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [28]:
#full does not allow to repeat the elements
np.full((2,3),((1,2,3),(4,5,6)))

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
#array operations
arr=np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


In [30]:
#calculating mean, median, mode,st deviation
print("mean")
a=arr.mean()
print(a)

#median
print("median")
a1=np.median(arr)
print(a1)

#mode
import scipy.stats as st
print("mode")
a3=st.mode(arr)
print(a3
      )
#std
print("standard deviation")
a4=arr.std()
print(a4)

mean
15.0
median
15.0
mode
ModeResult(mode=10, count=1)
standard deviation
3.1622776601683795


In [31]:
#reshape function:- used to reshape the array in another array form
# Create a 1D array with 12 elements
original_array = np.arange(12)
print("Original array")
print(original_array)

# Reshape the array into a 3x4 2D array
reshaped_array = original_array.reshape(3, 4)
print()
print('reshaped_array')
print(reshaped_array)

Original array
[ 0  1  2  3  4  5  6  7  8  9 10 11]

reshaped_array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
#argmin and argmax:-numpy.argmin() and numpy.argmax() to find the indices of the minimum and maximum values in an array, respectively.
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

# Find the index of the minimum value
index_of_min = np.argmin(arr)
print("the index of the minimum value")
print(index_of_min)#index is starting from 0

# Find the index of the maximum value
index_of_max = np.argmax(arr)
print("the index of the maximum value")
print(index_of_max)

the index of the minimum value
1
the index of the maximum value
5


In [33]:
#sorting the array
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

# Sort the array in ascending order
sorted_arr = np.sort(arr)
print("Sorted array in ascending order:", sorted_arr)

Sorted array in ascending order: [1 1 2 3 3 4 5 5 6 9]


In [34]:
#sorting acoording to the idexes
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

# Get the indices that would sort the array
indices = np.argsort(arr)
print("Indices for sorting:", indices)

Indices for sorting: [1 3 6 0 9 2 4 8 7 5]


In [35]:
#sorting based on the key values
names = np.array(["John", "Alice", "Bob", "Eve"])
scores = np.array([85, 90, 75, 95])#key values

# Sort the names based on scores
indices = np.lexsort((names, scores))
sorted_names = names[indices]
sorted_scores = scores[indices]
print("Sorted names:", sorted_names)
print("Sorted scores:", sorted_scores)

Sorted names: ['Bob' 'John' 'Alice' 'Eve']
Sorted scores: [75 85 90 95]


In [36]:
#sorting to according to row and column
arr = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])

# Sort the array by rows (axis=1)
sorted_by_rows = np.sort(arr, axis=1)
print("Sorted by rows:", sorted_by_rows)

# Sort the array by columns (axis=0)
sorted_by_columns = np.sort(arr, axis=0)
print("Sorted by columns:", sorted_by_columns)

Sorted by rows: [[1 3 4]
 [1 5 9]
 [2 5 6]]
Sorted by columns: [[1 1 4]
 [2 5 5]
 [3 6 9]]


In [37]:
#sorting based on the indexes
arr = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])

# Get the indices that would sort by rows (axis=1)
indices_by_rows = np.argsort(arr, axis=1)
print("Indices for sorting by rows:", indices_by_rows)

# Get the indices that would sort by columns (axis=0)
indices_by_columns = np.argsort(arr, axis=0)
print("Indices for sorting by columns:", indices_by_columns)

Indices for sorting by rows: [[1 0 2]
 [0 1 2]
 [0 2 1]]
Indices for sorting by columns: [[1 0 0]
 [2 1 2]
 [0 2 1]]


In [38]:
#rounding the elements
arr4=np.random.rand(3,3)
arr4.round(2)

array([[0.71, 0.02, 0.97],
       [0.83, 0.21, 0.18],
       [0.18, 0.3 , 0.52]])

In [39]:
#clipping:-numpy.clip() function to limit or "clip" the values of an array within a specified range. This function ensures that values in the array do not fall below a minimum value or exceed a maximum value.
#syntax:-numpy.clip(a, a_min, a_max, out=None)
arr = np.array([1, 5, 8, 10, 2, 3, 6])
clipped_arr = np.clip(arr, a_min=3, a_max=8)
#limiting the array min to 3 and max to 8

print(clipped_arr)

[3 5 8 8 3 3 6]


In [40]:
x=np.random.randint(1,20,10)
print(x)
x.clip(13,15)

[12 17 10 16 15 15 19 12  3  5]


array([13, 15, 13, 15, 15, 15, 15, 13, 13, 13])

In [41]:
#where:-This function can be used to return elements from one of two input arrays based on a specified condition.
condition = np.array([True, False, True])
#In this example, result will contain [1, 20, 3] because the condition is True for the first and third elements, so it selects values from arr1 and arr2 accordingly.
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = np.where(condition, arr1, arr2)
print(result)

[ 1 20  3]


In [42]:
#numpy.argwhere():

#This function returns the indices of elements that satisfy a given condition.


arr = np.array([1, 2, 3, 4, 5])
indices = np.argwhere(arr > 2)
print(indices)

[[2]
 [3]
 [4]]


In [43]:
arr=np.random.randint(1,30,20)
arr

array([19,  7, 21,  9,  7, 18,  4, 25, 28, 14, 18, 26,  9, 26, 21,  2, 20,
       28, 15, 28])

In [44]:
np.where(arr>20,0,arr)#the which is gretaer then 20 will be replaced by 0 and rest will be same

array([19,  7,  0,  9,  7, 18,  4,  0,  0, 14, 18,  0,  9,  0,  0,  2, 20,
        0, 15,  0])

In [45]:
np.where(arr>20,0,1) #np.where(condition,true,false) printing 0 if value is>20 and for rest 1

array([1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [46]:
#set operations
arr1=np.random.randint(1,20,10)
arr2=np.random.randint(1,20,10)
print(arr1,"\n",arr2)

[ 7 12  8 15  3 14 17  4 18  8] 
 [ 4  2  6 10  4 18 12  2 10  4]


In [47]:
#insertion:- getting the common elements from both the array above
np.intersect1d(arr1,arr2)

array([ 4, 12, 18])

In [48]:
#setdifference:-The numpy.setdiff1d() function in NumPy is used to find the set difference between two arrays, which means it returns the values that are present in the first array but not in the second array.
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

result = np.setdiff1d(arr1, arr2)

print(result)

[1 2]


In [49]:
np.setdiff1d(arr2,arr1)#value in array 2 but not in 1

array([6, 7])

In [50]:
#union
np.union1d(arr2,arr1)

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
#setxor1d:- it returns values that are unique to each of the two arrays.
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

result = np.setxor1d(arr1, arr2)

print(result)

[1 2 6 7]


In [52]:
#Dimension changing
#reshape:-numpy.reshape() function, which allows you to change the shape of an existing array while keeping the same data.

# Create a 1D array with 12 elements
original_array = np.arange(12)

# Reshape the array into a 3x4 2D array
reshaped_array = original_array.reshape(3, 4)

print(reshaped_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [53]:
#Transpose:-(.T) attribute to transpose a 2D array, which effectively switches the rows and columns.

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Transpose the array
transposed_arr = arr.T

print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [54]:
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
#flatten and ravel:-.flatten() and .ravel(), can be handy when you need to convert multi-dimensional arrays into a 1D format for various data processing and analysis tasks.
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Flatten the array
arr_1d = arr_2d.flatten()

print(arr_1d)

[1 2 3 4 5 6]


In [56]:
#ravel()
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

arr_1d = arr_2d.ravel()

print(arr_1d)

[1 2 3 4 5 6]


In [57]:
#flatting using for loop
for i in arr.flat:
    print(i,end=' ')

1 2 3 4 5 6 

In [58]:
#size of the array:-.size attribute to determine the number of elements in the array.

# Assuming "zrrzy" is a NumPy array
arr1 = np.array([1, 2, 3, 4, 5, 6])

# Get the size (number of elements) of the array
array_size = arr1.size

print("Size of the 'arr1' array:", array_size)

Size of the 'arr1' array: 6


In [59]:
#itemsize:-itemsize attribute in NumPy is used to determine the size (in bytes) of each element in a NumPy array.

# Create a NumPy array
arr = np.array([1, 2, 3], dtype=np.float32)

# Get the item size
element_size = arr.itemsize

print("Size of each element in the array:", element_size, "bytes")

Size of each element in the array: 4 bytes


In [60]:
#nbytes:-nbytes attribute in NumPy is used to determine the total memory usage (in bytes) of a NumPy array, considering the size and data type of the array's elements. It provides the complete memory consumption of the array.
# Create a NumPy array
arr = np.array([1, 2, 3], dtype=np.float32)

# Get the total memory usage of the array
total_memory_usage = arr.nbytes

print("Total memory usage of the array:", total_memory_usage, "bytes")

Total memory usage of the array: 12 bytes


In [61]:
#numpy.zeros_like():- It is a function creates a new array with the same shape as the input array, filled with zeros.

# Create an example array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a new array with the same shape, filled with zeros
zero_array = np.zeros_like(original_array)

print(zero_array)

[[0 0 0]
 [0 0 0]]


In [62]:
np.zeros_like(arr)

array([0., 0., 0.], dtype=float32)

In [63]:
#numpy.ones_like():- It is a function creates a new array with the same shape as the input array, filled with ones.

# Create an example array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a new array with the same shape, filled with ones
one_array = np.ones_like(original_array)

print(one_array)

[[1 1 1]
 [1 1 1]]


In [64]:
#iteration:-To perform an opertaion on a thing number of times

#Using a for loop:-
arr = np.array([1, 2, 3, 4, 5])

for element in arr:
    print(element)

1
2
3
4
5


In [65]:
#Using list comprehensions:-
arr = np.array([1, 2, 3, 4, 5])

squared_elements = [x**2 for x in arr]
print(squared_elements)

[1, 4, 9, 16, 25]


In [66]:
#Using NumPy functions for element-wise operations:-

arr = np.array([1, 2, 3, 4, 5])

squared_elements = np.square(arr)
print(squared_elements)

[ 1  4  9 16 25]


In [67]:
#Using NumPy functions for iteration

arr = np.array([[1, 2], [3, 4]])

for x in np.nditer(arr):
    print(x)

1
2
3
4


In [68]:
#combinig two arrays together:-
#numpy.concatenate(): This function combines two or more arrays along an existing axis. You can specify the axis along which the concatenation should occur.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate along the default axis (axis=0, row-wise)
combined = np.concatenate((arr1, arr2))

print(combined)

[1 2 3 4 5 6]


In [69]:
#numpy.vstack() and numpy.hstack(): These functions are used to vertically stack (vstack) or horizontally stack (hstack) arrays. They work well when you want to stack arrays together along different axes.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertically stack arrays
vertically_stacked = np.vstack((arr1, arr2))

# Horizontally stack arrays
horizontally_stacked = np.hstack((arr1, arr2))

print("Vertically stacked:")
print(vertically_stacked)

print("Horizontally stacked:")
print(horizontally_stacked)

Vertically stacked:
[[1 2 3]
 [4 5 6]]
Horizontally stacked:
[1 2 3 4 5 6]


In [70]:
#numpy.stack(): This function is used to stack arrays along a new axis, creating a new dimension in the result.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack arrays along a new axis (axis=0)
stacked = np.stack((arr1, arr2), axis=0)

print(stacked)

[[1 2 3]
 [4 5 6]]


In [71]:
#numpy.column_stack() and numpy.row_stack(): These functions are similar to hstack and vstack, respectively, but they create a 2D array by stacking 1D arrays.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack arrays as columns
column_stacked = np.column_stack((arr1, arr2))

# Stack arrays as rows
row_stacked = np.row_stack((arr1, arr2))

print("Column stacked:")
print(column_stacked)

print("Row stacked:")
print(row_stacked)

Column stacked:
[[1 4]
 [2 5]
 [3 6]]
Row stacked:
[[1 2 3]
 [4 5 6]]


In [72]:
#splitting
#numpy.split(), numpy.hsplit(), and numpy.vsplit() functions. These functions allow you to divide an array along specified axes or at specific positions.

arr = np.array([1, 2, 3, 4, 5, 6])

# Split the array into 3 equal sub-arrays along axis 0 (row-wise)
sub_arrays = np.split(arr, 3)

print(sub_arrays)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [73]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Split the array into 3 equal sub-arrays along columns (column-wise)
sub_arrays = np.hsplit(arr, 3)

print(sub_arrays)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [74]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split the array into 3 equal sub-arrays along rows (row-wise)
sub_arrays = np.vsplit(arr, 3)

print(sub_arrays)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
